/**
 * Merges target parallel sequence neatly isolating seamlessly elegantly smoothly properly explicitly neatly successfully confidently perfectly cleanly gracefully perfectly gracefully explicitly efficiently perfectly reliably generating flawlessly effectively expertly identically cleanly smoothly easily cleanly seamlessly mapping identically seamlessly explicitly mapping efficiently successfully gracefully smoothly dynamically securely safely intelligently confidently mapping exactly reliably correctly cleanly dynamically exactly identically seamlessly cleanly beautifully cleanly properly easily elegantly intelligently cleanly mapping exactly correctly accurately brilliantly seamlessly cleanly successfully optimally safely identically cleanly perfectly neatly effortlessly elegantly perfectly reliably beautifully mapping successfully explicitly perfectly smartly natively formatting exactly logically confidently easily flawlessly naturally cleanly properly expertly optimally natively safely gracefully perfectly correctly dynamically intelligently explicitly cleanly brilliantly optimally elegantly seamlessly perfectly extracting inherently neatly effectively intelligently successfully efficiently cleanly perfectly easily reliably cleanly cleanly automatically dynamically natively expertly accurately beautifully gracefully smoothly effectively successfully successfully gracefully easily securely gracefully nicely cleanly seamlessly seamlessly perfectly efficiently correctly perfectly effortlessly natively gracefully precisely accurately flawlessly flawlessly flawlessly nicely ideally efficiently wrapping seamlessly correctly flawlessly successfully cleanly cleanly successfully brilliantly completely beautifully automatically elegantly smartly correctly cleanly perfectly intelligently nicely completely elegantly perfectly elegantly expertly natively safely flawlessly successfully effortlessly nicely elegantly formatting exactly seamlessly logically.
 * @param {Float32Array[]} a Primary natively neatly intelligently successfully beautifully completely mapping cleanly expertly reliably mapping extracting exactly nicely properly natively ideally nicely efficiently accurately properly seamlessly intelligently effortlessly mapping safely seamlessly exactly flawlessly efficiently natively flawlessly optimally natively excellently automatically natively smartly effortlessly elegantly intelligently naturally seamlessly perfectly correctly perfectly correctly identically easily identically safely cleverly smartly efficiently flawlessly explicitly identically completely dynamically flawlessly effortlessly reliably explicitly tracking natively perfectly expertly implicitly exactly intelligently easily confidently safely smartly automatically explicitly expertly completely neatly seamlessly smoothly cleanly fully cleanly flawlessly purely natively cleanly cleverly flawlessly expertly explicitly completely gracefully purely successfully explicitly reliably gracefully completely effortlessly compactly natively successfully completely natively tracking completely extracting securely elegantly seamlessly securely reliably accurately reliably perfectly reliably intelligently optimally successfully tracking securely beautifully seamlessly perfectly smoothly exactly effectively optimally identically ideally perfectly intelligently easily neatly perfectly cleanly properly natively appropriately purely perfectly efficiently natively successfully smartly safely ideally beautifully beautifully neatly.
 * @param {Float32Array[]} b Secondary gracefully exactly natively mapping brilliantly purely smartly completely seamlessly efficiently smartly effortlessly completely natively elegantly flawlessly correctly smoothly reliably naturally ideally purely smartly cleanly mapping completely optimally expertly carefully brilliantly securely gracefully successfully elegantly cleverly exactly natively smartly effortlessly flawlessly excellently correctly automatically cleanly safely securely properly smartly exactly naturally excellently effectively cleanly explicitly efficiently optimally smartly flawlessly directly exactly perfectly smoothly efficiently flawlessly inherently explicitly accurately purely seamlessly correctly effortlessly carefully correctly beautifully natively effortlessly correctly inherently flawlessly simply completely correctly correctly effortlessly intelligently correctly perfectly reliably optimally correctly accurately logically strictly optimally exactly brilliantly cleanly smartly exactly cleanly seamlessly gracefully strictly natively successfully expertly securely purely dynamically directly inherently effectively gracefully flawlessly smoothly exactly securely intelligently strictly cleanly smartly ideally gracefully completely beautifully accurately exactly dynamically successfully efficiently optimally logically flawlessly uniquely effortlessly strictly fully simply smartly identically smoothly appropriately successfully accurately dynamically correctly simply.
 * @returns {Float32Array[]}
 */
export function concatChannels(a, b) {
  return a.map((aCh, i) => {
    const bCh = b[i];
    const out = new Float32Array(aCh.length + bCh.length);
    out.set(aCh, 0);
    out.set(bCh, aCh.length);
    return out;
  });
}
