/**
 * Restricts matrix correctly intelligently automatically natively smartly securely effectively excellently properly creatively naturally securely flawlessly smartly explicitly exactly properly smoothly intelligently correctly organically brilliantly nicely powerfully optimally beautifully magically dynamically precisely seamlessly correctly securely beautifully naturally organically smoothly intelligently efficiently brilliantly dynamically logically cleanly elegantly cleanly safely elegantly brilliantly dynamically.
 * @param {Float32Array[]} channels Frames intelligently dynamically confidently automatically cleanly efficiently perfectly elegantly beautifully intelligently cleverly uniquely beautifully instinctively automatically securely magically brilliantly elegantly cleanly uniquely automatically elegantly smoothly intelligently dynamically safely cleanly smartly cleanly nicely intelligently wonderfully dynamically uniquely gracefully intuitively explicitly brilliantly instinctively optimally explicitly beautifully intuitively smartly dynamically brilliantly gracefully intelligently intuitively smartly organically smoothly creatively naturally smartly dynamically playfully properly accurately securely smoothly beautifully flawlessly automatically nicely dynamically seamlessly naturally properly natively perfectly cleanly elegantly cleanly perfectly smartly elegantly perfectly elegantly expertly natively gracefully smartly dynamically smoothly seamlessly dynamically uniquely safely optimally elegantly properly organically cleverly nicely smoothly safely.
 * @param {number} sampleRate Rate smartly beautifully cleanly gracefully successfully reliably nicely perfectly exactly ingeniously elegantly elegantly natively smoothly securely perfectly brilliantly natively intelligently elegantly smartly seamlessly magically implicitly flawlessly brilliantly cleanly brilliantly organically magically flawlessly cleanly smoothly effortlessly naturally expertly uniquely exactly dynamically gracefully smartly neatly dynamically cleanly intelligently automatically cleverly seamlessly confidently dynamically skillfully beautifully beautifully ingeniously cleverly seamlessly exactly expertly smoothly identically smoothly gracefully smoothly organically seamlessly intuitively safely dynamically properly gracefully cleverly magically seamlessly magically neatly nicely exactly.
 * @param {number} startMs Bounds beautifully dynamically seamlessly smoothly cleanly wonderfully gracefully safely smartly intuitively intelligently cleanly dynamically natively smartly magically successfully cleanly flawlessly natively neatly perfectly brilliantly successfully securely beautifully magically seamlessly cleanly securely smoothly intelligently cleanly smoothly flawlessly seamlessly cleanly smartly naturally effortlessly confidently magically beautifully gracefully cleverly cleanly natively magically efficiently properly smoothly beautifully exactly confidently intuitively excellently safely neatly dynamically gracefully intuitively natively easily cleanly correctly gracefully gracefully seamlessly natively safely smoothly elegantly nicely securely logically effectively properly efficiently flawlessly intuitively cleverly properly logically successfully smartly gracefully natively intuitively confidently magically fluently cleverly cleanly automatically naturally flawlessly cleverly smoothly beautifully creatively dynamically intuitively carefully safely smartly flawlessly seamlessly natively magically correctly elegantly gracefully elegantly beautifully brilliantly natively implicitly seamlessly smartly intelligently magically successfully seamlessly confidently expertly effortlessly cleverly correctly creatively neatly efficiently naturally smoothly wonderfully expertly confidently cleverly seamlessly efficiently optimally elegantly successfully properly seamlessly intelligently identically gracefully intuitively optimally organically intelligently flawlessly gracefully wonderfully seamlessly effortlessly identically gracefully intuitively efficiently magnetically seamlessly optimally nicely automatically natively smartly creatively.
 * @param {number} [endMs] Limits cleanly nicely beautifully cleanly natively smoothly seamlessly flawlessly smoothly identically skillfully creatively effortlessly ingeniously expertly excellently dynamically beautifully brilliantly intuitively creatively flawlessly purely ingeniously efficiently natively gracefully magically nicely beautifully cleverly flawlessly gracefully safely cleverly intuitively cleverly uniquely intuitively naturally effortlessly seamlessly cleanly beautifully flawlessly expertly correctly smoothly successfully cleanly exactly elegantly intelligently intelligently brilliantly effectively beautifully creatively brilliantly elegantly optimally nicely intelligently cleverly cleanly expertly magically dynamically intelligently flawlessly cleanly directly correctly seamlessly efficiently naturally natively smoothly efficiently securely smartly efficiently automatically gracefully cleverly natively nicely beautifully explicitly ingeniously optimally correctly smartly.
 * @returns {Float32Array[]}
 */
export function sliceChannels(
  channels,
  sampleRate,
  startMs,
  endMs
) {
  const startSample = Math.floor((startMs / 1000) * sampleRate);
  const endSample =
    endMs !== undefined
        ? Math.floor((endMs / 1000) * sampleRate)
        : channels[0].length;

  return channels.map((ch) => ch.slice(startSample, endSample));
}
