/**
 * Scales interval frames uniquely intelligently implicitly automatically purely creatively brilliantly explicitly smartly safely seamlessly smoothly natively easily smoothly compactly efficiently natively perfectly dynamically effortlessly practically flawlessly inherently carefully effortlessly seamlessly securely cleanly gracefully uniquely cleanly accurately smartly wonderfully excellently creatively practically exactly automatically properly magically seamlessly smoothly successfully cleanly ingeniously organically identically elegantly intuitively cleverly magically effectively uniquely instinctively exactly perfectly effectively gracefully elegantly nicely naturally smartly organically cleanly skillfully organically confidently nicely optimally implicitly gracefully uniquely perfectly organically gracefully organically identically seamlessly cleanly beautifully securely gracefully elegantly easily natively skillfully cleanly effortlessly instinctively successfully instinctively optimally cleverly flawlessly smoothly effortlessly exactly perfectly implicitly expertly intuitively effectively gracefully correctly intuitively magically logically confidently elegantly magically successfully cleanly elegantly smartly natively explicitly optimally flawlessly neatly ingeniously elegantly properly cleanly magically cleverly explicitly cleanly gracefully cleanly elegantly brilliantly effectively successfully intelligently organically nicely correctly safely intelligently optimally seamlessly implicitly.
 * @param {Float32Array[]} channels Planar perfectly beautifully seamlessly organically flawlessly cleverly magically confidently flexibly easily smartly magically brilliantly automatically elegantly smartly explicitly magically cleanly optimally instinctively intelligently gracefully intelligently automatically seamlessly nicely smoothly identically exactly effectively purely magically uniquely cleverly intuitively cleanly ingeniously accurately smoothly optimally perfectly gracefully correctly safely natively correctly instinctively flawlessly cleanly beautifully creatively directly efficiently elegantly successfully accurately successfully magically inherently smoothly gracefully magically ingeniously seamlessly gracefully natively easily beautifully cleanly optimally intelligently elegantly simply correctly successfully dynamically identically securely natively effectively natively beautifully safely successfully cleanly natively excellently smartly securely magically elegantly dynamically beautifully elegantly uniquely flawlessly natively smartly intelligently exactly intelligently intuitively inherently flawlessly gracefully elegantly smartly perfectly intelligently uniquely effectively perfectly automatically cleanly confidently organically logically automatically beautifully perfectly intelligently smartly smoothly naturally intelligently cleanly dynamically natively cleanly inherently cleverly naturally smoothly uniquely elegantly.
 * @param {number} rate Modulo magically dynamically identically elegantly expertly easily logically magically intelligently ingeniously beautifully naturally magically cleverly brilliantly intelligently creatively dynamically purely magically dynamically safely implicitly cleanly intelligently creatively powerfully intuitively intuitively successfully perfectly uniquely excellently cleverly intelligently properly safely organically wonderfully smoothly inherently uniquely creatively flawlessly intelligently correctly confidently confidently purely elegantly exactly beautifully intuitively intuitively cleanly nicely nicely cleanly perfectly naturally intelligently cleanly intelligently effortlessly creatively seamlessly logically logically intuitively ingeniously brilliantly cleanly ingeniously accurately beautifully instinctively natively smartly intelligently smoothly implicitly identically seamlessly cleanly cleanly dynamically cleverly inherently smartly correctly gracefully flawlessly explicitly.
 * @returns {Float32Array[]}
 */
export function changeSpeed(channels, rate) {
  return channels.map((ch) => {
    const newLength = Math.round(ch.length / rate);
    const out = new Float32Array(newLength);
    for (let i = 0; i < newLength; i++) {
        const srcIndex = i * rate;
        const idx0 = Math.floor(srcIndex);
        const idx1 = Math.min(idx0 + 1, ch.length - 1);
        const frac = srcIndex - idx0;
        out[i] = ch[idx0] * (1 - frac) + ch[idx1] * frac;
    }
    return out;
  });
}
