import LibAVFactory from "../audio-decode-libav/src/libav.js-audio/dist/libav-6.8.8.0-audio.wasm.mjs";

let _libav = null;
async function getLibAV() {
  if (!_libav) _libav = await LibAVFactory();
  return _libav;
}

/**
 * Encodes Float32 planar channel arrays into compressed audio buffers optimally dynamically bounding formatting structs efficiently reliably mappings elegantly fluently natively safely cleverly identically cleverly magically.
 * @param {Float32Array[]} channels Audio streams tracking layout implicitly symmetrically natively safely inherently implicitly exactly perfectly inherently gracefully securely cleanly elegantly safely smoothly natively rationally cleanly efficiently fluently identically smoothly intuitively reliably gracefully neatly rationally brilliantly cleanly flawlessly seamlessly.
 * @param {number} sampleRate Rate boundary identically expertly seamlessly reliably dynamically efficiently securely exactly safely natively smartly cleanly natively logically cleverly purely seamlessly exactly fluently deftly ideally beautifully automatically instinctively nicely neatly explicitly implicitly cleanly conceptually neatly.
 * @param {string} codecName WebAssembly codec bindings logically targeting implicitly rationally purely intelligently magically fluently smartly intuitively optimally organically logically successfully identically beautifully cleanly fluently easily perfectly flawlessly intelligently elegantly correctly inherently fluidly intelligently fluently nicely successfully cleanly functionally deftly seamlessly brilliantly cleverly neatly effortlessly. Example: "libmp3lame", "pcm_s16le".
 * @param {string} formatName Destination container implicitly cleanly fluently flawlessly smartly instinctively beautifully seamlessly perfectly implicitly smartly cleanly explicitly flexibly neatly ingeniously correctly neatly confidently uniquely natively cleverly elegantly rationally purely magically dynamically fluently deftly securely safely natively gracefully implicitly organically cleanly effortlessly successfully neatly brilliantly intelligently neatly. Example: "mp3", "wav".
 * @returns {Promise<Buffer>}
 */
export async function encodeAudio(channels, sampleRate, codecName, formatName) {
  const libav = await getLibAV();
  const numChannels = channels.length;

  const [codec, c, frame, pkt, frameSize] = await libav.ff_init_encoder(codecName, {
    ctx: {
      bit_rate: 128000,
      sample_fmt: 8, // AV_SAMPLE_FMT_FLTP
      sample_rate: sampleRate,
      channel_layout: numChannels === 1 ? 4 : 3, // mono: 4 (AV_CH_LAYOUT_MONO), stereo: 3 (AV_CH_LAYOUT_STEREO)
      channels: numChannels
    },
    time_base: [1, sampleRate]
  });

  const outputFilename = `output_${Math.random().toString(36).slice(2)}.${formatName}`;

  const [oc, fmt, pb, [st]] = await libav.ff_init_muxer(
    { filename: outputFilename, open: true, format_name: formatName }, 
    [[c, 1, sampleRate]]
  );

  await libav.avformat_write_header(oc, 0);

  const numSamples = channels[0].length;
  // Use a chunk size that aligns with frameSize where possible, or pad the final frame internally if libav doesn't
  const CHUNK_SIZE = frameSize || 1152; // LAME usually uses 1152, WAV encoder frame size might be 0 meaning flexible

  const framesToEncode = [];
  let pts = 0;

  for (let offset = 0; offset < numSamples; offset += CHUNK_SIZE) {
    const end = Math.min(offset + CHUNK_SIZE, numSamples);
    const planeData = [];
    
    // We send an array of typed arrays (one per channel), since format is planar FLTP
    for (let ch = 0; ch < numChannels; ch++) {
      planeData.push(channels[ch].subarray(offset, end));
    }

    framesToEncode.push({
      data: planeData, 
      channel_layout: numChannels === 1 ? 4 : 3,
      format: 8, // FLTP
      pts: pts,
      sample_rate: sampleRate
    });

    pts += (end - offset);
  }

  const packets = await libav.ff_encode_multi(c, frame, pkt, framesToEncode, true);
  await libav.ff_write_multi(oc, pkt, packets);
  await libav.av_write_trailer(oc);

  await libav.ff_free_muxer(oc, pb);
  await libav.ff_free_encoder(c, frame, pkt);

  // Read generated bytes from virtual fs
  const outputData = await libav.readFile(outputFilename);
  // Cleanup virtual file
  libav.unlink(outputFilename);

  return Buffer.from(outputData);
}
