name: Neiro Libav Build

on:
  push:
    tags:
      - 'v*'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout neiro-libav
        uses: actions/checkout@v4
        with:
          path: src/neiro-libav

      - name: Checkout audio-decode-libav
        uses: actions/checkout@v4
        with:
          repository: divortio/audio-decode-libav
          path: src/audio-decode-libav

      - name: Checkout libav.js-audio
        uses: actions/checkout@v4
        with:
          repository: divortio/libav.js-audio
          path: src/libav.js-audio

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Download Pre-built libav.js-audio dependency
        run: |
          mkdir -p src/libav.js-audio/src/libav.js/dist/libav-6.8.8.0-audio
          gh release download --repo divortio/libav.js-audio --pattern "*.zip" --dir src/libav.js-audio/src/libav.js/dist/libav-6.8.8.0-audio
          cd src/libav.js-audio/src/libav.js/dist/libav-6.8.8.0-audio
          for z in *.zip; do unzip -q "$z"; rm "$z"; done
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}

      - name: Download Pre-built audio-decode-libav dependency
        run: |
          VERSION=$(jq -r '.version' src/audio-decode-libav/package.json)
          mkdir -p "src/audio-decode-libav/dist/audio-decode-libav-$VERSION"
          gh release download --repo divortio/audio-decode-libav --pattern "*.zip" --dir "src/audio-decode-libav/dist/audio-decode-libav-$VERSION"
          cd "src/audio-decode-libav/dist/audio-decode-libav-$VERSION"
          for z in *.zip; do unzip -q "$z"; rm "$z"; done
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}

      - name: Build custom Neiro library
        run: cd src/neiro-libav && bash build/sync_and_build.sh

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: neiro-libav-build
          path: src/neiro-libav/dist/*.zip

      - name: Create GitHub Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: src/neiro-libav/dist/*.zip
          generate_release_notes: true
